#!/usr/bin/perl -w
  print"\n signing in your usename and password:\n";
  print "username :\n";
  my $usename=<STDIN>;
  chomp $usename;
  print "password:\n";
  my $password=<STDIN>;
  chomp $password;
  my (%filename)=(
  "$usename" => "$password",
);

