#!/usr/bin/perl -w
use strict;
use warnings;
my @nucleotides=('A','C','G','T');
for (my $i=0;$i<10;++$i){
print randomnucleotide(@nucleotides), " ";
}
print"\n";
exit;
sub randomnucleotide{
my (@nucs)=@_;
return $nucs[rand @nucs];
}

